// Handles all GitHub API interactions: fetching PR files and posting review comments.


/** Filename patterns that add noise without review value — skipped during diff filtering. */
const IGNORED_PATTERNS = [
  /^package-lock\.json$/,
  /\.png$/,
  /\.jpg$/,
  /\.svg$/,
  /\.lock$/,
  /\.min\.js$/,
];

/**
 * Executes an async function with exponential backoff retry logic.
 */
async function withRetry(fn, retries = 3, delayMs = 1000) {
  for (let i = 0; i < retries; i++) {
    try {
      return await fn();
    } catch (error) {
      if (i === retries - 1) {
        console.error(`[API_FAILURE] Exhausted ${retries} retries: ${error.message}`);
        throw error;
      }
      console.warn(`[API_RETRY] Attempt ${i + 1} failed, retrying in ${delayMs}ms: ${error.message}`);
      await new Promise(resolve => setTimeout(resolve, delayMs));
      delayMs *= 2;
    }
  }
}

/**
 * Fetches the changed files for a pull request and returns a filtered list of
 * reviewable diffs. Skips files with no patch (e.g. binaries), deleted files,
 * and files matching common noise patterns (lock files, minified JS, images).
 *
 * @param {Octokit} octokit       - Authenticated Octokit instance
 * @param {string}  owner         - Repository owner (user or org)
 * @param {string}  repo          - Repository name
 * @param {number}  pull_number   - Pull request number
 * @returns {Promise<Array<{ filename: string, patch: string, status: string }>>}
 *   Filtered array of changed files, or an empty array on failure.
 */
async function getPRDiff(octokit, owner, repo, pull_number) {
  try {
    const files = await withRetry(() => octokit.paginate(octokit.pulls.listFiles, {
      owner,
      repo,
      pull_number,
      per_page: 100,
    }));

    const validFiles = files.filter((file) => {
      // Skip files with no patch content (e.g. binary files)
      if (file.patch === undefined) return false;

      // Skip deleted files — nothing to review in a removal
      if (file.status === "removed") return false;

      // Skip noisy files that don't benefit from LLM review
      if (IGNORED_PATTERNS.some((pattern) => pattern.test(file.filename))) {
        return false;
      }

      return true;
    });
    
    // Scale safety: Limit to max 30 files per run
    let finalFiles = validFiles;
    if (finalFiles.length > 30) {
      console.warn(`[FILES_LIMIT_APPLIED] PR has ${finalFiles.length} valid files. Truncating to 30.`);
      finalFiles = finalFiles.slice(0, 30);
    }

    return finalFiles.map(({ filename, patch, status }) => ({ filename, patch, status }));
  } catch (error) {
    console.error(`[getPRDiff] Failed to fetch PR files: ${error.message}`);
    return [];
  }
}

/**
 * Submits a pull request review containing one or more inline code comments.
 * All comments are posted atomically as a single review event.
 *
 * @param {Octokit} octokit                              - Authenticated Octokit instance
 * @param {string}  owner                                - Repository owner (user or org)
 * @param {string}  repo                                 - Repository name
 * @param {number}  pull_number                          - Pull request number
 * @param {Array<{ path: string, line: number, body: string }>} comments - Inline comments to post
 * @param {string}  commitId                             - SHA of the latest commit in the PR
 * @param {string}  summaryBody                          - Top-level PR summary generated by the Intelligence Gate
 * @returns {Promise<void>}
 */
async function postReviewComments(octokit, owner, repo, pull_number, comments, commitId, summaryBody = "🤖 Argus — powered by Groq (Llama 3.3 70B)") {
  if (!comments || comments.length === 0) {
    console.log("No issues found");
    return;
  }

  try {
    await withRetry(() => octokit.pulls.createReview({
      owner,
      repo,
      pull_number,
      commit_id: commitId,
      event: "COMMENT",
      body: summaryBody,
      comments: comments.map(({ path, line, body }) => ({
        path,
        line,
        body,
        side: "RIGHT",
      })),
    }));

    console.log(`[postReviewComments] Posted ${comments.length} review comment(s) on PR #${pull_number}.`);
  } catch (error) {
    console.error(`[postReviewComments] Failed to post review: ${error.message}`);
  }
}

module.exports = { getPRDiff, postReviewComments };
